version: "3.9"

services:
  # the name of our service
  app:
    build:
      # use the current directory for the context
      context: .
      args:
        - DEV=true
    ports:
      # port mapping
      - "8000:8000"
    volumes:
      # map our ./app directory to the /app directory of the container
      - ./app:/app
    # command that is used to run the service  
    command: >
      sh -c "python manage.py runserver 0:8000"
